### PR TITLE
Add pep8 check as part of travis build.

### PR DESCRIPTION
**Pull request by akshar-raaj**

### CODE REVIEW

**Comment by shabda** [comment]
@akshar-raaj : You will need to update requirements to install pep8.

**Comment by akshar-raaj** [comment]
@shabda Installing pep8 separately as part of travis. Don't want to keep it in requirement because it's not used by django-secure-login code.

**Comment by shabda** [comment]
@akshar-raaj : You will need to update the PR to take the new code layout in consideration.

**Comment by tuxcanfly** [comment]
Has been merged

**Pull request closed without merging**
